### ISSUE TITLE
貌似不支持index属性

### ISSUE THREAD

**Issue by Valar103769** [linxianxi/react-router-auth-plus#1]
https://github.com/Valar103769/react-dashboard
我的项目用你这个,就不知道哪里卡住了, 报错信息也没有,能帮忙看一下?

**Comment by linxianxi** [comment]
应该是版本问题，我这个 react-router 是 6.3x 版本的，现在最新是 6.4 版本了。看了下，6.4 改动很大。

**Comment by linxianxi** [comment]
明天我研究一下 6.4 版本的

**Comment by Valar103769** [comment]
我主要是想用那个loader, 但是loader跟pretectedRouter 一起搞, 再用来生成菜单感觉还是太麻烦了, 你可以提供两个工具函数吗
- 传入routes和权限判断的函数
```js
routes = [
{path:“home”,name:“首页”, element:<Home / >}
]
```
内部使用Suspense和ProdectRoute拦截下,然后一个新的routes, 然后我直接给createBrowserRoutes使用, 

第二个函数生成菜单数组, 返回下 过滤了index:true项和 能够访问的菜单 
生成菜单这里, v6里的router.routes里 打印不出name和icon, 得需要从传入的源头routes开始搞, 我就没搞了

**Comment by linxianxi** [comment]
稍微看了一下文档，感觉这应该叫 v7 比较适合，改动太大了，一个路由库还要管数据获取和修改数据。

**Comment by Valar103769** [comment]
vue-router也可以请求数据,但是不能管理, 感觉他的数据没办法删除,有个revalidate 那是重新调用的意思吧?

**Comment by linxianxi** [comment]
更新到 1.3.0 版本，先根据 example 里面例子来写，文档还没空写

**Comment by linxianxi** [comment]
更新到 1.3.1 版本，根据 readme 或者 example 文件夹里的写就 ok 了。

**Comment by linxianxi** [comment]
看这个项目吧，更新了，比较全。 https://github.com/linxianxi/spirit-admin

**Comment by Valar103769** [comment]
> 看这个项目吧，更新了，比较全。 https://github.com/linxianxi/spirit-admin

好
