### ISSUE TITLE
 route loader 中的 redirect 会失效

### ISSUE THREAD

**Issue by vaynevayne** [linxianxi/react-router-auth-plus#4]
具体可以看这个 issue https://github.com/remix-run/react-router/issues/10863

听react-router 官网的意思是需要在组件外调用 createBrowserRouter

估计做权限这一块, 还是得参考react-native 那些 demo中的处理方式, 先获取用户信息,再初始化组件

**Comment by linxianxi** [comment]
没用过 loader，不知道啥情况，react-router 改动有点大。倒不用先获取用户信息,再初始化组件，挺多办法的。

**Comment by vaynevayne** [comment]
有没了解过其他 router 库?
这个库感觉太坑了

**Comment by linxianxi** [comment]
直接上 next.js 吧

**Comment by vaynevayne** [comment]
> 直接上 next.js 吧

他的路由菜单支持权限? 支持动态生成? 
貌似只能根据代码文件来吧, 就算能, 也比这个复杂

**Comment by vaynevayne** [comment]
<img width="1008" alt="image" src="https://github.com/linxianxi/react-router-auth-plus/assets/124666577/d37d2005-4582-4930-beb6-a1dcfaeef3de">

服了 竟然说你这个库设计的不好, 我觉得 react-router 设计的才差, 大大不如 vue-router,  react 生态里 期待一个新的 router 库吧

**Comment by linxianxi** [comment]
我这个是在 loader 出之前做的，后来 6.4 loader 出了之后它改动很大，可能就不怎么适合了

**Comment by linxianxi** [comment]
我自己重新用 loader 搭了一个后台管理，比较容易的，没用这个

**Comment by vaynevayne** [comment]
> 我自己重新用 loader 搭了一个后台管理，比较容易的，没用这个

能分享下代码吗? @linxianxi

**Comment by linxianxi** [comment]
没拆出来单独个模版。你弄个 loader 中 redirect 失效的最简复现吧，我看下有没办法

**Comment by linxianxi** [comment]
就这样
<img width="512" alt="image" src="https://github.com/linxianxi/react-router-auth-plus/assets/47104575/d9183a07-a414-421c-9546-4dfc0f48d3b7">
